### ISSUE TITLE
Readme inconsitency.

### ISSUE THREAD

**Issue by CMLL** [pindexis/marker#2]
In the README you put Ctrl-Space as the default key binding to invoke marker get, but looking at the code, is actually Ctrl-@

    marker_key_get=${MARKER_KEY_GET:-'\C-@'}

Just that. Great work, very useful.

**Comment by pindexis** [comment]
'@' refers to the space character.

Thanks for the feedback :)

**Comment by CMLL** [comment]
Uhm, pretty weird. In what OS are you trying it? I'm using Ubuntu 14.04 and what actually work with C-@ is Ctrl-@. Are you on OS-X? Other thing is that I'm using zsh, but for the comment in marker.sh I figured that wouldn't be the problem.

**Comment by pindexis** [comment]
I'm also on Ubuntu 14.04:
In my case, '\C-@' is identified by both Ctrl+Space and Ctr+@

Try running `cat` command and press on Ctrl+space. let me know the output.

Thanks.

**Comment by CMLL** [comment]
Nope, only autocompletes with Ctrl-@, but not with Ctrl-Space. I'm trying to remember if something I use sets Ctrl-Space as a keybing, and have a coworker installing marker to try and replicate.

**Comment by CMLL** [comment]
Ahh, another thing, when installing, git clone said I didn't had permissions, had to use http.

**Comment by pindexis** [comment]
Updated Readme instructions to clone using https. Thanks

**Comment by pindexis** [comment]
I guess this can be closed now.
