### ISSUE TITLE
bash: read: read error: 0: Input/output error

### ISSUE THREAD

**Issue by mmatthers** [pindexis/marker#34]
When i hit ctrl+space i get this error which freezes up the terminal window.  
My bash version is here:
GNU bash, version 4.4.0(1)-release (x86_64-pc-linux-gnu)
Any ideas?
Thanks

**Comment by podkot** [comment]
found out that commenting line 14 in bin/marker.sh solves the problem for me:

```bash
# stty raw -echo min 0
```

**Comment by masmarius** [comment]
thx @podkot, worked like a charm!

**Comment by pindexis** [comment]
fixed in latest master(please re-clone or pull)
