### ISSUE TITLE
Unescaped left brace in regex is deprecated, passed through in regex

### ISSUE THREAD

**Issue by C0rWin** [pindexis/marker#37]
I've installed marker on OSX + zsh following the instructions, now when I'm pressing `Ctrl-T` getting following error on terminal screen:

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/{{ <-- HERE .+?}}/ at -e line 1.
```

What could be possible reason for this error and how I can fix it?

PS. I've tried both iTerm and Terminal.

**Comment by xsysroot** [comment]
C0rWin I do not know much programming languages, but i change in file ~/.marker/bin/marker.sh next string:
before: match=$(echo "$BUFFER" | perl -nle 'print $& if m{{{.+?}}}' | head -n 1)
after: match=$(echo "$BUFFER" | perl -nle 'print $& if m{\{\{.+?\}\}}' | head -n 1)
and this work !

**Comment by et2010** [comment]
@xsysroot Thanks for the tip, but it doesn't work for me.

**Comment by thejustsoul** [comment]
Edit `~/.marker/bin/marker.sh`

Find:
`match=$(echo "$BUFFER" | perl -nle 'print $& if m{{{.+?}}}' | head -n 1)`
Replace:
`match=$(echo "$BUFFER" | perl -nle 'print $& if m{\{\{.+?\}\}}' | head -n 1)`

Find:
`match=$(echo "$READLINE_LINE" | perl -nle 'print $& if m{{{.+?}}}' | head -n 1)`
Replace:
`match=$(echo "$READLINE_LINE" | perl -nle 'print $& if m{{\{.+?\}}}' | head -n 1)`

From https://github.com/haxrbyte/marker/commit/49f3738f1b0a0d025e44f1fdaccfa4f4ea01dff7

**Comment by et2010** [comment]
@thejustsoul This fix works! Thanks!

**Comment by pindexis** [comment]
Sorry guys for not being active for a while, I'll do the upgrade. thanks @thejustsoul
