### ISSUE TITLE
Where are the customized actions saved?

### ISSUE THREAD

**Issue by lijingjiang** [pindexis/marker#38]
Hi, 

Just want to know if I saved a command using marker, where can I find the file which contains this command. 

I try to trace through the source code by myself, but I'm not an expert in python or shell. Hope someone can help me out.

Thank you again for this amazing project!

**Comment by mpdatx** [comment]
They live in $MARKER_DATA_HOME/user_commands.txt.  MARKER_DATA_HOME for me is ~/.local/share/marker
