### ISSUE TITLE
change 'ctrl-space' shortcut to something else?

### ISSUE THREAD

**Issue by biocyberman** [pindexis/marker#55]
I have 'ctrl-space' on macOS as input method switching shortcut. How do I change 'ctrl-space' for marker to something else to avoid collision?

**Comment by x4base** [comment]
I use Ctrl-f as the hotkey. In this case, add `MARKER_KEY_GET="\C-f"` to `~/.bash_profile`, and it 
 should work.
Like this:
```
MARKER_KEY_GET="\C-f"
[[ -s "$HOME/.local/share/marker/marker.sh" ]] && source "$HOME/.local/share/marker/marker.sh"
```

As described in  README.md : `You can customize key binding using environment variables, respectively with MARKER_KEY_GET, MARKER_KEY_MARK and MARKER_KEY_NEXT_PLACEHOLDER.`

**Comment by mahiki** [comment]
I think you can close this issue, the env keybinding assignments solve.
