### ISSUE TITLE
Tab in shell is starting a new mark

### ISSUE THREAD

**Issue by hipposareevil** [pindexis/marker#6]
In zsh if I do a TAB it starts a new mark:
~> ls TAB
turns into
~>  marker mark --command='ls '
command: ls
Alias?:

Is there a way to reconfigure so TAB doesn't start a new mark?

**Comment by pindexis** [comment]
Weird, TAB shouldn't start a new mark.
Ctrl+k is the shortcut responsible for creating a new mark.
Maybe you're(or a plugin you're using) mapping TAB to CTRL+K which is causing this issue.
You can change the shortcuts used by Marker by setting the current variables in your .zshrc :
```
MARKER_KEY_MARK='\C-k'
MARKER_KEY_GET='\C-@' #\C-@ is also C-space
MARKER_KEY_NEXT_PLACEHOLDER='\C-t'
```

**Comment by hipposareevil** [comment]
So, I was in ZSH and had changed the MARKER_KEY_MARK to '\C-i' because CTRL+K was in my muscle memory for kill line.  '\C-i' has the TAB complete issue.  I changed it over to '\C-o' and everything works!

awesome tool!

thanks
