### ISSUE TITLE
Install gives error on Yosemite

### ISSUE THREAD

**Issue by flodi** [pindexis/marker#7]
I've upgraded bash to 4.x and echo $BASH_VERSION prints 4.3.33(1)-release but doing a ./install.py I get this error:
Couldn't extract bash version, please report the issue
Installation failed

**Comment by pindexis** [comment]
can you execute `bash --version` and post the output?
It's the command I'm using to get the version of BASH.

**Comment by flodi** [comment]
I get this:

ThinAir:log flodi$ bash --version
GNU bash, versione 4.3.33(1)-release (x86_64-apple-darwin14.1.0)
Copyright (C) 2013 Free Software Foundation, Inc.
Licenza GPLv3+: GNU GPL versione 3 o successiva <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by pindexis** [comment]
Ah, I should have thought about non-english systems.
Install script updated. it should work fine now.
Thanks for reporting
